// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://reqwrfmbwcxwomcdyzpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlcXdyZm1id2N4d29tY2R5enBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0NzA1MDQsImV4cCI6MjA1MzA0NjUwNH0.WfGnbCVFemvH8EoDTCkm4h9T9paFw-J1z04rrQp-BS0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);